### ISSUE TITLE
BEST 17/18 prioriteter

### ISSUE THREAD

**Issue by Mortal** [TK-IT/meta#15]
INKA skriver: "Vi synes faktisk at de 3 ting de tidligere bestyrelser har sat på lyder som en god idé. Vores prioritet på de opgaver er."

1. [x] #2 SMTP-server, så vi kan skrive fra vores @TK.dk mails
1. [x] #3 Evaluerings wiki, lyder som en super smart idé
1. [ ] #7 Sangbogsgenerator
1. [ ] https://github.com/TK-IT/web/issues/106 Universalt søgefelt på adminsiden

INKA skriver: "Dog synes vi at i skal tage opgaver først hvis i mener at det er hurtigere, og det giver mere mening for jer. Læs: Vi stoler på i gør det godt."

**Comment by tjavsi** [comment]
Jeg har lige tilføjet søge på titler på admin siden, dette er en ting vi i BEST også godt kunne tænke os. 
[#16](https://github.com/TK-IT/meta/issues/16)

**Comment by tjavsi** [comment]
Ville det måske være muligt at give mindst SEKR(hvis ikke hele best) adgang til https://taagekammeret.dk/regnskab/profile/ . Så de har mulighed for at søge titler, men ikke ændre i noget regnskab ? 

Som en form for midlertidig løsning
